##############################################
# configuration file for annotation pipeline #
##############################################

# Input
genome:
    file: "/share/pool/CompGenomVert/RefGenomes/fPhoPho/fPhoPho.hap1.20220427.fa"
    haplotype: "hap1"

# - folder containing rna input files
# Important: must be a folder and must end in a slash "/"
# folder should only contain zipped fastq files that all have the same extension
# the names of the two paires should be the same and differ only on the last character
# of the basename which should be a 1 or 2
# example: rna_file1.fq.gz, rna_file2.fq.gz
# - strandedness of sequencing
rnaseq:
    folder: "/share/pool/genofish_and_chips/testannotation/resources/data/rnaseq/"
    type: "Stranded"

# Consolidated protein fasta sequences
prot_db: "/share/pool/genofish_and_chips/testannotation/resources/RefDB/protein_newheader.fa"

# Containers
containers:
    repeat_modeler: "/share/scientific_bin/singularity/containers/dfam-tetools.sif"
    repeat_masker: "/share/scientific_bin/singularity/containers/dfam-tetools.sif"
    braker3: "/share/scientific_bin/singularity/containers/braker3.sif"

# Repeat Library Configuration
# For DFAM RepBase libraries, use the Latin name of the species.
# For RepBase or other libraries, use the absolute path to the fasta file library
repeat_library: "danio"

# Braker3 configuration
# Augustus species/run name and cfg file
augustus:
    species: zebrafish
    cfg: "utils/augustus_custom_extrinsic.cfg"

# BRAKER3 run
# - choose genemark mode to use (see readme file and braker github page for details)
# - edit BRAKER options that are not related to directory handling or input
# and add any additional options you want to include
BRAKER3: 
    mode: "ETP"
    user_options: "--AUGUSTUS_ab_initio \
        --softmasking_off \
        --UTR=off \
        --gff3 \
        --verbosity=4 \
        --nocleanup \
        "

# Necessary modules
modules:
    conda: "anaconda3/2022.05"
    trf: "trf/4.10.0-rc.2"
    star: "STAR/2.7.10a"
    augustus: "augustus/3.3.3"

# BUSCO
busco:
    lineage: "actinopterygii_odb10"
    directory: "/share/pool/databases/busco_downloads_v5/"
